### PR TITLE
WIP: adding FFT for field object

### PR DESCRIPTION
**Pull request by stetie**
currently, only 2D fields are supported. Generalization for 1D and 3D should be straight forward and will be added in the near future. Restores the functionality lost by refactoring in commit cc85c42.
A good test cases is needed to check if this function is working properly. This should be done before merging it into master.

### CODE REVIEW

**Comment by stetie** [comment]
from my point of view, it is ready to be merged into dev. A good test case is still missing. Closes issue #34 .

**Comment by skuschel** [comment]
Thanks for the PR. But some things still need to be adressed:
* Make sure the units are defined or can be canonically inferred. 
  * Particularly: `k0` is requested but never used. 
  * The label says `FFT` of, but `abs(FFT)**2` is created. We should probably have an `fft` function which can do lots of stuff, and add later usabiity functions like `spectrum` or `spectral_phase` which are just using `fft`. However, this requires `fft` to be defined carefully!
* Test Cases and Examples need to be added.
* In more dimensions I dont understand yet how you define which axis to transform. Maybe you can have a look how `numpy.fft.fftn` does it and make this fftn function behave the same. That will also give us a definition of the inteded behaviour for free. If it turns out to be not usefor for some reason, it will be more work to define what the function should do.
* Once done, tested and documente, please send the PR directly to `master`.

**Comment by stetie** [comment]
I think I've addressed all the points made above. If you're also happy with it, I would send a new pull request to `master`.

**Comment by skuschel** [comment]
I did not quite get back to you, sorry for that! That looks quite good, but I still have a few points, mainly about generality and error messages:
* the `fft` can mean a lot of stuff. It does the normal numpy fft  which should be noted to be absolute clear about the normalization. Also the arguments can be much better explained to clearly say that `shiftaxis` can only be one axis, because the originating field is real -- oh and that needs to be checked!
* I find it confusing that the fft will only work with a real field but not backwards. this needs far more generality. The result is complex, so a back transform is impossible. 
* In general a fild can hold anything: electric field, magnetic field, energy density, particle density... whatever. The `spectrum` function however is silently including a facotor of `0.5*epsilon0`. The only way for the user to spot this is to read through the source, which must be avoided.

We should have a discussion to clarify what the general case exactly is. Without giving it too much thought, I suspect an `fft` and an `ifft` function which will work on complex fields both ways will be a good start. Spectra or real values are specialized problems.

**Comment by skuschel** [comment]
Replaced by #73

**Pull request closed without merging**
