### PR TITLE
add new default species for QED module.

### PR DESCRIPTION
**Pull request by MerlinPendragon**
Hi guys, I simply added 3 more default species for QED module of EPOCH. 
But the scalar property should change for photon since its mass equals 0.
Any idea?

### CODE REVIEW

**Comment by skuschel** [comment]
Hi @MerlinPendragon 
thanks a lot for your contribution. I agree that these default names are not captured, but probably used within the QED context.
Regarding the scalar property of photons: I took a quick look into the epoch manual but didnt see how the photon energies are written and what properties you will need to access. Maybe you can explain and we can work out a solution.

**Comment by skuschel** [comment]
I will merge this as its a change in itself. Maybe you like to open an issue to disucuss how other photon properties can be accessed?

**Comment by skuschel** [comment]
just a hint: Github doesnt understand that your commit was done by you as a github user. If you like to be listed under https://github.com/skuschel/postpic/graphs/contributors you will need to link your email adress from your gitconfig to your github account. :)

**Comment by MerlinPendragon** [comment]
Thank you! It's mainly about the energy of photon. I will probably add a new scalar property for photon and open another pull request.

**Pull request merged**
