### PR TITLE
WIP: Added an improved version of `time_profile_at_plane`

### PR DESCRIPTION
**Pull request by Ablinne**
Should be much faster

### CODE REVIEW

**Comment by Ablinne** [comment]
@stetie I can't remember if you have tested this already. Can it get merged?

**Comment by Ablinne** [comment]
@skuschel It's been a long time since I've been working on this. My notebooks where I did the integration testing beyond the unit tests are buried quite deep. I was about 99% sure that the new method is correct, but I was waiting on Stefan to test it in his notebooks where he used to use the original version. I guess he never came around to it.

Maybe we could just change the names of the methods and leave the original method as it was and give this new, faster method a new name. Than users can opt-in to the new method and see for themselves if it yields results compatible to the old one.

**Comment by skuschel** [comment]
@Ablinne thanks for your reply! If these methods do exactly the same, why not adding a test which compares the results of both methods? We could also have the test run as a benchmark to see how much speed it actually gains. What do you think?

I also changed the test from travis to gh-actions, so the branch will need to merge from master before test will start working.

**Comment by stetie** [comment]
Totally forgot about it, sorry!
+1 for creating a test case. If I test it manually, I might not test all possible combinations of input parameters.

**Comment by Ablinne** [comment]
@skuschel, @stetie They are not exactly the same, in fact the algorithms are completely different. Aliased modes will behave differently in both algorithms and boundary conditions are different. So it is not super straight-forward to compare the results of the old and new functions. In fact these points strongly speak for having both methods. There is already a test that executes the function, but it does no verification of the result (class TestKspace in test_helper.py). If one wants to directly compare both one needs an example with good resolution (no aliasing) and field content that is well separated from the boundary.

**Comment by Ablinne** [comment]
out of time for today, let's see when i get to look for a way to test the results of the functions to some extent. The fields produced by the dummy reader are not suitable as input. Probably need to manually put a gaussian pulse in a box or something.

**Pull request merged**
