### PR TITLE
Updating smileih5.py

### PR DESCRIPTION
**Pull request by VinithSamson11**

### CODE REVIEW

**Comment by VinithSamson11** [comment]
Code integrity is tested using run-tests.py (passed all tests)
Detailed Doc-stings were added for main functions.
And code's performance and working were tested using jupyter notebook.

**Comment by skuschel** [comment]
Oh and please update the `Changelog.md` file under `current master` that a reader for smilei version whatever has been added including a link to the smilei repo

**Comment by VinithSamson11** [comment]
The Changes you mentioned have been made. The version I have used is smilei v4.8.

**Comment by VinithSamson11** [comment]
The smileih5.py file were tested with latest SmileiPIC (v5.0) & Happi version. The test data were dumped from Smilei version v5.0 and the the output values are compared with latest corresponding version of Happi. The percentage errors are in the order of ~10^-13 %.

**Pull request merged**
